version: '3.8'


services:
  discovery:
    image: consul:1.9
    ports:
      - "8500:8500"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rbnb-reservation
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p
    ports:
      - "27017:27017"