version: '3.3'
services:
  discovery:
    image: consul:1.9
    ports:
      - 8500:8500

  # utilisateur-service:
  #   build: ./Rbnb.UtilisateurService
  #   ports:
  #     - "9002:80"
  #   depends_on:
  #     - mysql-utilisateur-service
  mysql-utilisateur-service:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'UtilisateurService'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'p'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - ./dump/onstart-utlisateur-service-mysql.sql:/docker-entrypoint-initdb.d/create.sql

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # DB_ADDR: mysql-keycloak
      #DB_USER: keycloak
      #DB_PASSWORD: keycloak
      #DB_PORT: 3307
      #DB_DATABASE: keycloak
      #KEYCLOAK_IMPORT: /tmp/export-realm.json
    ports:
      - "9001:8080"
    #volumes:
    # - ../dump/export-realm.json:/tmp/export-realm.json
    #depends_on:
    #  - mysql-keycloak

    #  mysql-keycloak:
    #    image: mysql
    #    environment:
    #      MYSQL_ROOT_PASSWORD: admin
    #      MYSQL_USER: keycloak
    #      MYSQL_PASSWORD: keycloak
    #      MYSQL_DATABASE: keycloak
    #    ports:
    #      - "3307:3306"
