version: '3.3'

services:
  discovery:
    image: consul:1.9
    ports:
      - 8500:8500
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 15672:15672
        - 5672:5672

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "9000:9009"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
        -DCONSUL_PORT=8500
    depends_on:
      - discovery
      - utilisateur-service
      - logement-service
      - reservation-service
      - review-service

  utilisateur-service:
    build:
      context: ./Rbnb.UtilisateurService
    ports:
      - "9002:80"
    environment:
      - ConnectionStrings_DefaultConnection=Server=mysql-utilisateur-service;Port=3307;Database=UtilisateurService;User=user;Password=1234
      - consul_name=rbnb-utilisateur-service
      - consul_host=discovery
      - consul_port=9002
      - consul_address=http://discovery:8500
      - keycloak_host=https://rbnb-keycloak.azurewebsites.net/auth
      - keycloak_client=rbnb-client
    depends_on:
      - discovery
      - mysql-utilisateur-service

  mysql-utilisateur-service:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'UtilisateurService'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'p'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - ./dump/onstart-utlisateur-service-mysql.sql:/docker-entrypoint-initdb.d/create.sql

  logement-service:
    build:
      context: ./rbnb-logement-service
    ports:
      - "9003:9003"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
        -DCONSUL_PORT=8500

        -DKEYCLOAK_SERVER_URL=https://rbnb-keycloak.azurewebsites.net/auth
        -DKEYCLOAK_REALM=rbnb
        -DKEYCLOAK_CLIENT=rbnb-client

        -DMYSQL_HOST=mysql-logement-service
        -DMYSQL_PORT=3306
        -DMYSQL_DB=rbnb-logement
        -DMYSQL_USER=root
        -DMYSQL_PWD=p
    depends_on:
      - discovery
      - mysql-logement-service

  mysql-logement-service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: rbnb-logement
      MYSQL_ROOT_PASSWORD: p
    ports:
      - "3308:3306"

  reservation-service:
    build:
      context: ./rbnb-reservation-service
    ports:
      - "9004:9004"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
        -DCONSUL_PORT=8500

        -DKEYCLOAK_SERVER_URL=https://rbnb-keycloak.azurewebsites.net/auth
        -DKEYCLOAK_REALM=rbnb
        -DKEYCLOAK_CLIENT=rbnb-client

        -DMONGO_HOST=mongo-reservation-service
        -DMONGO_PORT=27017
        -DMONGO_DB=rbnb-reservation
        -DMONGO_USER=admin
        -DMONGO_PW=p
    depends_on:
      - discovery
      - mongo-reservation-service

  mongo-reservation-service:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rbnb-reservation
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p
    ports:
      - "27017:27017"


  review-service:
    build:
      context: ./rbnb-review-service
    ports:
      - "9005:9005"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
        -DCONSUL_PORT=8500

        -DKEYCLOAK_SERVER_URL=https://rbnb-keycloak.azurewebsites.net/auth
        -DKEYCLOAK_REALM=rbnb
        -DKEYCLOAK_CLIENT=rbnb-client

        -DMYSQL_HOST=mysql-review-service
        -DMYSQL_PORT=3306
        -DMYSQL_DB=rbnb-review
        -DMYSQL_USER=root
        -DMYSQL_PWD=p
    depends_on:
      - discovery
      - mysql-review-service

  mysql-review-service:
    platform: linux/amd64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: rbnb-review
      MYSQL_ROOT_PASSWORD: p
    ports:
      - "3309:3306"


