version: '3.8'


services:
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
     # DB_ADDR: mysql-keycloak
      #DB_USER: keycloak
      #DB_PASSWORD: keycloak
      #DB_PORT: 3307
      #DB_DATABASE: keycloak
      #KEYCLOAK_IMPORT: /tmp/export-realm.json
    ports:
      - "9001:8080"
    #volumes:
     # - ./keycloak:/tmp
    #depends_on:
    #  - mysql-keycloak

#  mysql-keycloak:
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_USER: keycloak
#      MYSQL_PASSWORD: keycloak
#      MYSQL_DATABASE: keycloak
#    ports:
#      - "3307:3306"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rbnb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p
    ports:
      - "27017:27017"
  mysql-app:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: rbnb
      MYSQL_ROOT_PASSWORD: p
    ports:
      - "3306:3306"
