version: '3.1'
# networks:
#   keycloak-network:
services:
  #   keycloak:
  #     image: jboss/keycloak
  #     environment:
  #       KEYCLOAK_USER: admin
  #       KEYCLOAK_PASSWORD: admin
  #       DB_ADDR: mysql
  #       DB_USER: keycloak
  #       DB_PASSWORD: keycloak
  #       DB_PORT: "3307"
  #       DB_DATABASE: keycloak
  #       KEYCLOAK_IMPORT: /tmp/import-realm.json
  #     ports:
  #       - 8085:8080
  #     volumes:
  #       - ./keycloak:/tmp
  #     depends_on:
  #       - mysql
  #     networks:
  #       - keycloak-network
  #   mysql:
  #     image: mysql
  #     environment:
  #       MYSQL_ROOT_PASSWORD: admin
  #       MYSQL_USER: keycloak
  #       MYSQL_PASSWORD: keycloak
  #       MYSQL_DATABASE: keycloak
  #     ports:
  #       - 3307:3306
  #     networks:
  #       - keycloak-network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p
    ports:
      - 27017:27017
  mysql-app:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'rbnb'
      MYSQL_ROOT_PASSWORD: p
    ports:
      - 3306:3306
