version: '3.8'


services:
  discovery:
    image: consul:1.9
    ports:
      - "8500:8500"

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # DB_ADDR: mysql-keycloak
      #DB_USER: keycloak
      #DB_PASSWORD: keycloak
      #DB_PORT: 3307
      #DB_DATABASE: keycloak
      #KEYCLOAK_IMPORT: /tmp/export-realm.json
    ports:
      - "9001:8080"
      #volumes:
      # - ../dump/export-realm.json:/tmp/export-realm.json
    #depends_on:
    #  - mysql-keycloak

  #  mysql-keycloak:
  #    image: mysql
  #    environment:
  #      MYSQL_ROOT_PASSWORD: admin
  #      MYSQL_USER: keycloak
  #      MYSQL_PASSWORD: keycloak
  #      MYSQL_DATABASE: keycloak
  #    ports:
  #      - "3307:3306"

  mysql-logement-service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: rbnb-logement
      MYSQL_ROOT_PASSWORD: p
    ports:
      - "3308:3306"
