
spring:

  application:
    name: rbnb-api-gateway

  cloud:

    consul:
      discovery:
        register: true
        hostname: ${CONSUL_HOSTNAME:localhost}
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      loadbalancer:
        ribbon:
          enabled: false

    gateway:
      discovery:
        locator:
          enabled: true

      routes:

        - id: rewritepath_route_utilisateur_service
          uri: lb://rbnb-utilisateur-service
          predicates:
            - Path=/api/utilisateur/**
          filters:
            - RewritePath=/api/utilisateur(?<segment>/?.*), /Utilisateur$\{segment}
            - PreserveHostHeader
        - id: rewritepath_route_logement_service
          uri: lb://rbnb-logement-service
          predicates:
            - Path=/api/logement/**
            - Path=/api/equipement/**
            - Path=/api/categorie/**
          filters:
            - RewritePath=/api/logement(?<segment>/?.*), /logement$\{segment}
            - RewritePath=/api/equipement(?<segment>/?.*), /equipement$\{segment}
            - RewritePath=/api/categorie(?<segment>/?.*), /categorie$\{segment}
            - PreserveHostHeader
        - id: rewritepath_route_review_service
          uri: lb://rbnb-review-service
          predicates:
            - Path=/api/review/**
          filters:
            - RewritePath=/api/review(?<segment>/?.*), /review$\{segment}
            - PreserveHostHeader
        - id: rewritepath_route_reservation_service
          uri: lb://rbnb-reservation-service
          predicates:
            - Path=/api/reservation/**
          filters:
            - RewritePath=/api/reservation(?<segment>/?.*), /reservation$\{segment}
            - PreserveHostHeader
server:
  port: 9009
