version: '3.3'
services:
  mysql-user-service:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'p'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      #volumes:
      #- ./schema.sql:/docker-entrypoint-initdb.d/schema.sql