POST localhost:8084/account/compte
Content-Type: application/x-www-form-urlencoded

idOwner=max&libelle=binance&type=crypto

> {%
client.global.set("idCompte", response.headers.valueOf("idCompte"));
client.global.set("idOwner", response.headers.valueOf("idOwner"));
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Le compte n'a pas été créé");
});
%}

###

GET localhost:8084/account/compte/{{idCompte}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Le compte n'existe pas");
});
%}
###

PUT localhost:8084/account/compte/{{idCompte}}
Content-Type: application/x-www-form-urlencoded

libelle=pea&type=action

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Le compte n'existe pas");
});
%}
###

GET localhost:8084/account/{{idOwner}}/compte

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Le compte n'existe pas");
});
%}
###

DELETE localhost:8084/account/compte/{{idCompte}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Le compte n'existe pas");
});
%}
###
DELETE localhost:8084/account/{{idOwner}}/compte

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Le compte n'existe pas");
});
%}
###



GET localhost:8084/account/compte/{{idCompte}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Le compte ne dervait pas exister");
});
%}
###

DELETE localhost:8084/account/compte/{{idCompte}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Le compte ne devrait pas exister");
});
%}

###

